name: Docker Build on ZeroTier

on:
  push:
    branches:
      - master     # 当 master 分支有推送时触发
  schedule:
    - cron: '0 */6 * * *'  # 每6小时检查一次
  workflow_dispatch:      # 允许手动触发

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          df -hT $PWD
          docker build \
            --network host \
            --tag zerotier-planet-build:latest \
            --build-arg TAG=main \
            .

